import {auth,db,firebaseReady} from '../firebase/firebase-config.js';
import {signInWithEmailAndPassword,signOut,onAuthStateChanged,setPersistence,browserLocalPersistence,browserSessionPersistence,sendPasswordResetEmail} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {doc,getDoc,collection,getDocs,query,orderBy,limit,startAfter,addDoc,updateDoc,deleteDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {withLoading} from './utils/loading.js';
import {compressImage} from './utils/image-compressor.js';
const $=s=>document.querySelector(s);const modal=$('#admin-modal'),loginView=$('#admin-login-view'),dashboardView=$('#admin-dashboard-view'),content=$('#admin-modal-content');
const svg=paths=>`<svg class="admin-icon" viewBox="0 0 24 24" aria-hidden="true">${paths}</svg>`;
const icons={folder:svg('<path d="M3 7h6l2 2h10v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>'),file:svg('<path d="M6 3h9l3 3v15H6zM9 11h6M9 15h6M9 7h2"/>'),chart:svg('<path d="M5 20V10M12 20V4M19 20v-7"/>'),plus:svg('<path d="M12 5v14M5 12h14"/>'),user:svg('<circle cx="12" cy="8" r="3"/><path d="M5 21c0-4 3-6 7-6s7 2 7 6"/>'),grid:svg('<rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/>'),image:svg('<rect x="3" y="4" width="18" height="16" rx="2"/><path d="m6 16 4-4 3 3 2-2 3 3M8 8h.01"/>'),globe:svg('<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/>'),save:svg('<path d="M5 3h12l2 2v16H5zM8 3v6h8V3M8 21v-7h8v7"/>'),light:svg('<path d="M9 18h6M10 22h4M8 14a7 7 0 1 1 8 0c-1 1-1 2-1 3H9c0-1 0-2-1-3z"/>')};
const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)};
let pageCursor=null;let activeTab='overview';
function close(){modal.hidden=true}function open(){modal.hidden=false}
$('#profile-menu').onclick=()=>{$('#profile-dropdown').hidden=!$('#profile-dropdown').hidden};$('#open-admin').onclick=open;$('#footer-admin').onclick=open;$('#admin-access').onclick=open;$('#close-admin').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
async function isAdmin(user){if(!user||!firebaseReady)return false;const record=await getDoc(doc(db,'users',user.uid));return record.exists()&&record.data().isAdmin===true}
function setTab(tab){activeTab=tab;document.querySelectorAll('[data-admin-tab]').forEach(button=>button.classList.toggle('active',button.dataset.adminTab===tab));renderTab().catch(()=>toast('Não foi possível carregar esta área.'))}
document.querySelectorAll('[data-admin-tab]').forEach(button=>button.onclick=()=>setTab(button.dataset.adminTab));
function table(items,headers,rows){const wrap=document.createElement('div');wrap.className='admin-list';const element=document.createElement('table');const isProjects=headers[0]==='Projeto';const tableHeaders=isProjects?[...headers,'Ações']:headers;const head=document.createElement('thead');head.innerHTML=`<tr>${tableHeaders.map(h=>`<th>${h}</th>`).join('')}</tr>`;const body=document.createElement('tbody');items.forEach(item=>{const tr=document.createElement('tr');rows(item).forEach(value=>{const td=document.createElement('td');if(value instanceof Node)td.append(value);else td.textContent=value;tr.append(td)});if(isProjects){const td=document.createElement('td');td.append(projectActions(item));tr.append(td)}body.append(tr)});element.append(head,body);wrap.append(element);return wrap}
async function getPage(collectionName,sort='ordem'){const constraints=[orderBy(sort,'desc'),limit(10)];if(pageCursor)constraints.push(startAfter(pageCursor));const snap=await getDocs(query(collection(db,collectionName),...constraints));pageCursor=snap.docs.at(-1)||null;return snap.docs.map(d=>({id:d.id,...d.data()}))}
function previewProject(project){const view=$('#project-modal');const viewContent=$('#modal-content');viewContent.replaceChildren();const title=document.createElement('h2');title.textContent=project.nome||'Projeto';const category=document.createElement('p');category.textContent=project.categoria||'Sem categoria';const description=document.createElement('p');description.textContent=project.descricaoCurta||'Sem descrição.';viewContent.append(title,category,description);if(project.imagem){const image=document.createElement('img');image.src=project.imagem;image.alt=project.nome||'Projeto';image.className='admin-preview-image';viewContent.prepend(image)}view.hidden=false}
function projectActions(project){const actions=document.createElement('div');actions.className='project-crud-actions';const open=document.createElement('button');open.type='button';open.className='crud-open';open.innerHTML=`${icons.file} Abrir`;open.onclick=()=>previewProject(project);const edit=document.createElement('button');edit.type='button';edit.className='crud-edit';edit.innerHTML=`${svg('<path d="m4 20 4-1 11-11-3-3L5 16zM14 6l3 3"/>')} Editar`;edit.onclick=()=>{content.replaceChildren(projectForm(project))};const remove=document.createElement('button');remove.type='button';remove.className='crud-delete';remove.innerHTML=`${svg('<path d="M4 7h16M10 11v5M14 11v5M6 7l1 14h10l1-14M9 7V4h6v3"/>')} Excluir`;remove.onclick=async()=>{if(!confirm(`Excluir o projeto "${project.nome}"? Esta ação não pode ser desfeita.`))return;try{remove.disabled=true;await withLoading(()=>deleteDoc(doc(db,'projects',project.id)),'Excluindo projeto…');toast('Projeto excluído.');setTab('projects')}catch(error){toast(error.message||'Não foi possível excluir o projeto.')}finally{remove.disabled=false}};actions.append(open,edit,remove);return actions}
function confirmImageRemoval(){return new Promise(resolve=>{const overlay=document.createElement('div');overlay.className='admin-image-confirm';overlay.innerHTML=`<div class="admin-image-confirm-box" role="dialog" aria-modal="true" aria-labelledby="admin-image-confirm-title"><h3 id="admin-image-confirm-title">Excluir imagem</h3><p>Tem certeza que deseja excluir esta imagem?</p><div><button class="admin-image-cancel" type="button">Cancelar</button><button class="admin-image-delete" type="button">Excluir imagem</button></div></div>`;const close=result=>{document.removeEventListener('keydown',onKey);overlay.remove();resolve(result)};const onKey=event=>{if(event.key==='Escape')close(false)};overlay.querySelector('.admin-image-cancel').onclick=()=>close(false);overlay.querySelector('.admin-image-delete').onclick=()=>close(true);overlay.onclick=event=>{if(event.target===overlay)close(false)};document.addEventListener('keydown',onKey);document.body.append(overlay);overlay.querySelector('.admin-image-cancel').focus()})}
function projectImages(project){return [...new Set([project?.imagem,...(Array.isArray(project?.imagens)?project.imagens:[])].filter(image=>typeof image==='string'&&image.trim()))]}
function projectForm(project=null){
  const editing=Boolean(project);
  let images=projectImages(project);
  const form=document.createElement('form');
  form.className='admin-project-form';
  form.innerHTML=`<div class="admin-form-heading"><span class="admin-form-symbol">${editing?svg('<path d="m4 20 4-1 11-11-3-3L5 16zM14 6l3 3"/>'):icons.plus}</span><div><h3>${editing?'Editar projeto':'Novo projeto'}</h3><p>${editing?'Atualize as informações do projeto selecionado.':'Adicione um novo projeto ao seu portfólio.'}</p></div><aside class="admin-tip"><b>${icons.light} Dica</b><span>Preencha as informações abaixo para ${editing?'atualizar':'criar'} o projeto.</span></aside></div><label><span>${icons.user} Nome do projeto</span><input name="nome" placeholder="Digite o nome do projeto" required maxlength="100"></label><label><span>${icons.grid} Categoria</span><select name="categoria" required><option value="">Selecione uma categoria</option><option>Landing page</option><option>Site institucional</option><option>Sistema web</option><option>Loja virtual</option><option>Manutenção</option><option>Outro</option></select></label><label><span>${icons.file} Descrição curta</span><textarea name="descricaoCurta" placeholder="Escreva uma breve descrição sobre o projeto..." required maxlength="300"></textarea></label><label class="admin-image-field"><span>${icons.image} Imagem do projeto <small>(opcional, será comprimida em WebP)</small></span><input name="imagem" type="file" accept="image/*"><em>${icons.image} Clique para escolher um arquivo ou arraste e solte aqui</em></label><div class="admin-image-gallery" hidden><strong>${icons.image} <span>Imagens do projeto</span></strong><div class="admin-image-gallery-list"></div></div><label class="admin-publish-field"><span><b>${icons.globe} Publicar no site</b><small>O projeto ficará visível no seu site.</small></span><span class="admin-toggle"><input name="publicado" type="checkbox" checked><span aria-hidden="true"></span></span></label><button class="button primary" type="submit">${icons.save} ${editing?'Salvar alterações':'Salvar projeto'}</button>`;
  const gallery=form.querySelector('.admin-image-gallery');
  const galleryTitle=gallery.querySelector('strong span');
  const galleryList=gallery.querySelector('.admin-image-gallery-list');
  const renderGallery=()=>{gallery.hidden=!editing||images.length===0;galleryTitle.textContent=`Imagens do projeto (${images.length})`;galleryList.replaceChildren(...images.map((source,index)=>{const item=document.createElement('figure');const image=document.createElement('img');image.src=source;image.alt=`Imagem ${index+1} do projeto ${project?.nome||''}`;image.loading='lazy';const remove=document.createElement('button');remove.type='button';remove.className='admin-image-remove';remove.setAttribute('aria-label',`Excluir imagem ${index+1}`);remove.innerHTML=svg('<path d="m6 6 12 12M18 6 6 18"/>');remove.onclick=async()=>{if(!await confirmImageRemoval())return;try{remove.disabled=true;const nextImages=images.filter((_,position)=>position!==index);await withLoading(()=>updateDoc(doc(db,'projects',project.id),{imagens:nextImages,imagem:nextImages[0]||''}),'Excluindo imagem…');images=nextImages;project.imagens=[...nextImages];project.imagem=nextImages[0]||'';renderGallery();toast('Imagem excluída com sucesso.')}catch(error){toast(error.message||'Não foi possível excluir a imagem.');remove.disabled=false}};item.append(image,remove);return item}))};
  if(project){form.nome.value=project.nome||'';form.categoria.value=project.categoria||'';form.descricaoCurta.value=project.descricaoCurta||'';form.publicado.checked=project.publicado===true}
  renderGallery();
  form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button[type="submit"]');try{button.disabled=true;const imageFile=form.imagem.files[0];const uploadedImage=imageFile?await withLoading(()=>compressImage(imageFile),'Comprimindo imagem…'):'';const savedImages=uploadedImage?[uploadedImage,...images.filter(image=>image!==uploadedImage)]:images;const imagem=savedImages[0]||'';const data={nome:form.nome.value.trim(),categoria:form.categoria.value.trim(),descricaoCurta:form.descricaoCurta.value.trim(),imagem,imagens:savedImages,publicado:form.publicado.checked};if(editing){await withLoading(()=>updateDoc(doc(db,'projects',project.id),data),'Salvando alterações…');toast('Projeto atualizado com sucesso.')}else{await withLoading(()=>addDoc(collection(db,'projects'),{...data,ordem:Date.now(),criadoEm:serverTimestamp()}),'Salvando projeto…');toast('Projeto salvo com sucesso.')}setTab('projects')}catch(error){toast(error.message||'Não foi possível salvar o projeto.')}finally{button.disabled=false}};
  return form
}
async function renderTab(){content.replaceChildren();pageCursor=null;if(activeTab==='overview'){const cards=[['Projetos','Gerencie os projetos exibidos no site, adicione novos conteúdos e mantenha tudo atualizado.',icons.folder,'Acessar projetos','projects'],['Orçamentos','Consulte os últimos pedidos, acompanhe orçamentos e gerencie suas solicitações.',icons.file,'Acessar orçamentos','quotes'],['Consultas','Dados carregados somente ao abrir cada aba, garantindo mais performance e agilidade.',icons.chart,'Acessar consultas','quotes']];const box=document.createElement('div');box.className='admin-summary';box.append(...cards.map(([title,description,icon,action,tab])=>{const card=document.createElement('article');card.className='admin-summary-card';card.innerHTML=`<i>${icon}</i><b>${title}</b><span>${description}</span><button type="button">${action} ${svg('<path d="M5 12h14M13 6l6 6-6 6"/>')}</button>`;card.querySelector('button').onclick=()=>setTab(tab);return card}));content.append(box);return}const name=activeTab==='projects'?'projects':'quotes';if(activeTab==='projects')content.append(projectForm());const loading=withLoading(()=>getPage(name,activeTab==='projects'?'ordem':'criadoEm'),'Carregando página do painel…');const items=await loading;if(activeTab==='projects')content.append(table(items,['Projeto','Categoria','Status'],item=>[item.nome||'Sem nome',item.categoria||'—',item.publicado?'Publicado':'Rascunho']));else content.append(table(items,['Nome','Tipo','Status'],item=>[item.nome||'—',item.tipoSistema||'—',item.status||'novo']));const tools=document.createElement('div');tools.className='admin-page-tools';const more=document.createElement('button');more.innerHTML=`${svg('<path d="M20 11a8 8 0 1 0 1.5 4.7M20 4v7h-7"/>')} Carregar mais`;more.onclick=async()=>{const next=await withLoading(()=>getPage(name,activeTab==='projects'?'ordem':'criadoEm'),'Carregando mais itens…');if(!next.length){more.disabled=true;more.textContent='Fim da lista';return}const extra=activeTab==='projects'?table(next,['Projeto','Categoria','Status'],item=>[item.nome||'Sem nome',item.categoria||'—',item.publicado?'Publicado':'Rascunho']):table(next,['Nome','Tipo','Status'],item=>[item.nome||'—',item.tipoSistema||'—',item.status||'novo']);content.insertBefore(extra,tools)};tools.append(more);content.append(tools)}
async function showAdmin(user){if(!await isAdmin(user)){await signOut(auth);throw new Error('Esta conta não tem autorização para o painel.')}loginView.hidden=true;dashboardView.hidden=false;setTab('overview')}
const loginForm=$('#admin-login-form');
const passwordInput=$('#admin-password');
const passwordToggle=$('#toggle-admin-password');
passwordToggle.addEventListener('click',()=>{const showing=passwordInput.type==='text';passwordInput.type=showing?'password':'text';passwordToggle.setAttribute('aria-label',showing?'Mostrar senha':'Ocultar senha');passwordToggle.setAttribute('aria-pressed',String(!showing));passwordInput.focus()});
$('#admin-forgot-password').addEventListener('click',async()=>{const email=loginForm.email.value.trim();if(!email)return toast('Digite seu e-mail para recuperar a senha.');if(!firebaseReady)return toast('Configure o Firebase antes de recuperar a senha.');try{await withLoading(()=>sendPasswordResetEmail(auth,email),'Enviando recuperação…');toast('Enviamos o link de recuperação para o seu e-mail.')}catch(error){toast(error.message||'Não foi possível enviar a recuperação de senha.')}});
loginForm.addEventListener('submit',async event=>{event.preventDefault();if(!firebaseReady)return toast('Configure o Firebase antes de entrar.');const button=event.currentTarget.querySelector('button[type="submit"]');try{button.disabled=true;const persistence=event.currentTarget.remember.checked?browserLocalPersistence:browserSessionPersistence;await setPersistence(auth,persistence);const result=await withLoading(()=>signInWithEmailAndPassword(auth,event.currentTarget.email.value.trim(),event.currentTarget.password.value),'Validando acesso…');await showAdmin(result.user)}catch(error){toast(error.message||'Não foi possível entrar.')}finally{button.disabled=false}});
$('#admin-logout').onclick=async()=>{await signOut(auth);dashboardView.hidden=true;loginView.hidden=false;content.replaceChildren();toast('Sessão encerrada.')};
if(firebaseReady)onAuthStateChanged(auth,async user=>{const button=$('#admin-access'),login=$('#open-admin');button.hidden=true;login.hidden=false;if(user&&await isAdmin(user)){button.hidden=false;login.hidden=true}});
