import {auth,db,firebaseReady} from '../firebase/firebase-config.js';
import {signInWithEmailAndPassword,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {doc,getDoc,collection,getDocs,query,orderBy,limit,startAfter,addDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {withLoading} from './utils/loading.js';
import {compressImage} from './utils/image-compressor.js';
const $=s=>document.querySelector(s);const modal=$('#admin-modal'),loginView=$('#admin-login-view'),dashboardView=$('#admin-dashboard-view'),content=$('#admin-modal-content');
const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)};
let pageCursor=null;let activeTab='overview';
function close(){modal.hidden=true}function open(){modal.hidden=false}
$('#profile-menu').onclick=()=>{$('#profile-dropdown').hidden=!$('#profile-dropdown').hidden};$('#open-admin').onclick=open;$('#footer-admin').onclick=open;$('#admin-access').onclick=open;$('#close-admin').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
async function isAdmin(user){if(!user||!firebaseReady)return false;const record=await getDoc(doc(db,'users',user.uid));return record.exists()&&record.data().isAdmin===true}
function setTab(tab){activeTab=tab;document.querySelectorAll('[data-admin-tab]').forEach(button=>button.classList.toggle('active',button.dataset.adminTab===tab));renderTab().catch(()=>toast('Não foi possível carregar esta área.'))}
document.querySelectorAll('[data-admin-tab]').forEach(button=>button.onclick=()=>setTab(button.dataset.adminTab));
function table(items,headers,rows){const wrap=document.createElement('div');wrap.className='admin-list';const element=document.createElement('table');const head=document.createElement('thead');head.innerHTML=`<tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr>`;const body=document.createElement('tbody');items.forEach(item=>{const tr=document.createElement('tr');rows(item).forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td)});body.append(tr)});element.append(head,body);wrap.append(element);return wrap}
async function getPage(collectionName,sort='ordem'){const constraints=[orderBy(sort,'desc'),limit(10)];if(pageCursor)constraints.push(startAfter(pageCursor));const snap=await getDocs(query(collection(db,collectionName),...constraints));pageCursor=snap.docs.at(-1)||null;return snap.docs.map(d=>({id:d.id,...d.data()}))}
function projectForm(){const form=document.createElement('form');form.className='admin-project-form';form.innerHTML='<h3>Novo projeto</h3><label>Nome<input name="nome" required maxlength="100"></label><label>Categoria<input name="categoria" required maxlength="50"></label><label>Descrição curta<textarea name="descricaoCurta" required maxlength="300"></textarea></label><label>Imagem do projeto <small>(opcional, será comprimida em WebP)</small><input name="imagem" type="file" accept="image/*"></label><label><input name="publicado" type="checkbox" checked> Publicar no site</label><button class="button primary" type="submit">Salvar projeto</button>';
form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button');try{button.disabled=true;const imageFile=form.imagem.files[0];const imagem=imageFile?await withLoading(()=>compressImage(imageFile),'Comprimindo imagem…'):'';await withLoading(()=>addDoc(collection(db,'projects'),{nome:form.nome.value.trim(),categoria:form.categoria.value.trim(),descricaoCurta:form.descricaoCurta.value.trim(),imagem,publicado:form.publicado.checked,ordem:Date.now(),criadoEm:serverTimestamp()}),'Salvando projeto…');toast('Projeto salvo com sucesso.');setTab('projects')}catch(error){toast(error.message||'Não foi possível salvar o projeto.')}finally{button.disabled=false}};return form}
async function renderTab(){content.replaceChildren();pageCursor=null;if(activeTab==='overview'){const box=document.createElement('div');box.className='admin-summary';box.append(...[['Projetos','Gerencie os projetos exibidos no site'],['Orçamentos','Consulte os últimos pedidos'],['Consultas','Dados carregados somente ao abrir cada aba']].map(([a,b])=>{const card=document.createElement('div');card.className='admin-summary-card';card.innerHTML=`<b>${a}</b><span>${b}</span>`;return card}));content.append(box);return}const name=activeTab==='projects'?'projects':'quotes';if(activeTab==='projects')content.append(projectForm());const loading=withLoading(()=>getPage(name,activeTab==='projects'?'ordem':'criadoEm'),'Carregando página do painel…');const items=await loading;if(activeTab==='projects')content.append(table(items,['Projeto','Categoria','Status'],item=>[item.nome||'Sem nome',item.categoria||'—',item.publicado?'Publicado':'Rascunho']));else content.append(table(items,['Nome','Tipo','Status'],item=>[item.nome||'—',item.tipoSistema||'—',item.status||'novo']));const tools=document.createElement('div');tools.className='admin-page-tools';const more=document.createElement('button');more.textContent='Carregar mais';more.onclick=async()=>{const next=await withLoading(()=>getPage(name,activeTab==='projects'?'ordem':'criadoEm'),'Carregando mais itens…');if(!next.length){more.disabled=true;more.textContent='Fim da lista';return}const extra=activeTab==='projects'?table(next,['Projeto','Categoria','Status'],item=>[item.nome||'Sem nome',item.categoria||'—',item.publicado?'Publicado':'Rascunho']):table(next,['Nome','Tipo','Status'],item=>[item.nome||'—',item.tipoSistema||'—',item.status||'novo']);content.insertBefore(extra,tools)};tools.append(more);content.append(tools)}
async function showAdmin(user){if(!await isAdmin(user)){await signOut(auth);throw new Error('Esta conta não tem autorização para o painel.')}loginView.hidden=true;dashboardView.hidden=false;setTab('overview')}
$('#admin-login-form').addEventListener('submit',async event=>{event.preventDefault();if(!firebaseReady)return toast('Configure o Firebase antes de entrar.');const button=event.currentTarget.querySelector('button');try{button.disabled=true;const result=await withLoading(()=>signInWithEmailAndPassword(auth,event.currentTarget.email.value.trim(),event.currentTarget.password.value),'Validando acesso…');await showAdmin(result.user)}catch(error){toast(error.message||'Não foi possível entrar.')}finally{button.disabled=false}});
$('#admin-logout').onclick=async()=>{await signOut(auth);dashboardView.hidden=true;loginView.hidden=false;content.replaceChildren();toast('Sessão encerrada.')};
if(firebaseReady)onAuthStateChanged(auth,async user=>{const button=$('#admin-access'),login=$('#open-admin');button.hidden=true;login.hidden=false;if(user&&await isAdmin(user)){button.hidden=false;login.hidden=true}});
